server:
  port: 9000
spring:
  thymeleaf:
    cache: false
  application:
    name: PersonWeb0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka


