server:
  port: 8088
spring:
  datasource:
    password: 123
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test_springboot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: PersonProvider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka
ProviderVersion: PersonProvider1
